#!/bin/dash
#===================================================#
# title       : desktop startup                     #
# author      : sunless47                           #
# description : script to exec on hyprland start up #
#===================================================#

# sound
pipewire 2> /dev/null &
pipewire-pulse 2> /dev/null &
wireplumber 2> /dev/null &

# wallpaper
wbg $HOME/stash/pics/sunless.png 2> /dev/null &

# # misc
# brightnessctl set 3% 2> /dev/null &
