#!/usr/bin/env bash
#=============================================#
# title       : cleaning cache                #
# date        : 2024-09-16                    #
# author      : sunless47                     #
# description : deleting unnecessary packages #
#=============================================#

# removing specific packages
pacman \
        --query \
        --quiet | \
fzf \
        --multi \
        --preview 'pacman -Qi {1}' | \
xargs \
        --no-run-if-empty \
        --open-tty \
sudo pacman \
        --remove \
        --nosave \
        --recursive

# # using paccache utility from pacman-contrib
# sudo paccache \
#         --remove \
#         --keep 0 \
#         --uninstalled

# pacman builtin option for cleaning cache
sudo pacman \
        --sync \
        --clean \
        --clean
